import './globals.css'
import ThemeProvider from "../components/ThemeProvider"
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import { Carousel } from '../components/CarouselProducts'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>

        <Navbar>

          {children}

        </Navbar >


      </ThemeProvider>
    </html>
  )
}
