import './globals.css'
import ThemeProvider from "../components/ThemeProvider"
import ThemeWrapper from "../components/ThemeWrapper"
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import { Carousel } from '../components/CarouselProducts'
import { Footer } from "../components/layout/Footer"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <ThemeProvider>


        <Navbar>
          <ThemeWrapper>
            {children}
            <Footer />
          </ThemeWrapper>
        </Navbar >

      </ThemeProvider>

    </html >
  )
}
